exclude: >
  \.cache|
  \.eggs|
  \.git|
  \.hg|
  \.mypy_cache|
  \.tox|
  \.venv|
  __pycache__|
  _build|
  docs|
  node_modules|
  venv
fail_fast: true

repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: detect-private-key
        exclude: .gitlab/ci/ssh_key
      - id: mixed-line-ending
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
      - id: pyupgrade
        args: [--py3-plus, --py36-plus]

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-pytest-style
          - flake8-implicit-str-concat
          - pep8-naming

# vim: set et ts=2 sw=2
